[package]
name = "wasm-julia"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
num-complex = { version = "0.2", default-features = false }
